---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    tenant: "default"
    vrf: "default"
    bd_name: "default"
    bd_ip: "1.1.1.1"
    bd_mask: "24"
    app_profile: "default"
    private: no
  tasks:
    - name: CREATE TENANT
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
      register: created_tenant
    - name: CREATE VRF
      aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        vrf_name: "{{ vrf }}"
        description: "VRF for Tenant Created Using Ansible"
      register: created_vrf
    - name: CREATE BRIDGE DOMAIN
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: '{{ tenant }}'
        vrf: '{{ vrf }}'
        bd: '{{ bd_name }}'
      register: created_bd
    - name: CREATE BD SUBMIT
      aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: '{{ tenant }}'
        bd: '{{ bd_name }}'
        gateway: '{{ bd_ip }}'
        mask: '{{ bd_mask }}'
      register: created_bd_subnet
    - name: CREATE AP
      aci_ap:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: '{{ tenant }}'
        app_profile: '{{ app_profile }}'
      register: created_app_profile

    - debug:
        msg: "[Status {{ created_tenant }}]"
        #msg: "[Status {{ created_tenant.status }} for tenant creation, Status {{ created_vrf.status }} for vrf creation, Status {{ created_bd.status }} for bridge domain creation, Status {{ created_bd_subnet.status }} for setting bridge domain subnet, Status {{ created_app_profile.status }} for app profile creation]"
